spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
#      import: "optional:configserver:http://localhost:8071"

#        - id: discovery-server
#          uri: http://localhost:8761/
#          predicates:
#            - Path=/eureka/web
#          filters:
#            - SetPath=/
#
#        - id: discovery-server-static
#          uri: http://localhost:8761/
#          predicates:
#            - Path=/eureka/**
#
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product/**
#
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/order/**
#
#        - id: inventory-service
#          uri: lb://inventory-service
#          predicates:
#            - Path=/api/inventory/**
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: http://localhost:8181/realms/microservice-realm/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true



info:
  app:
    name: "gateway-server"
    description: "gateserver for my ecommerce website"
    version: "1.0.0"

server:
  port: 9999



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000