version: '3.8'

services:
  configserver:
    networks:
      - my-network
    image: "vamsi9515/config-server:s1"
    container_name: configserver-ms
    ports:
      - "8071:8071"

  db:
    image: mysql:8.0.27
    networks:
      - my-network
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      DATABASE_PORT: 3306
  app:
    networks:
      - my-network
    image: vamsi9515/user-service:s1
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:8080
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/user-service_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_APPLICATION_NAME: "user-service"
    depends_on:
      - db
      - configserver

networks:
  my-network:
    driver: bridge