
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createTableIfNotExists=true
    username: root
    password: Vamsi@243
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  profiles:
    active: "dev"
  config:
    import: configserver:http://localhost:8071/

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#user:
#  message: "default-profile"


build:
  version: "1.0.0"


#
#logging:
#  level:
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

