spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createTableIfNotExists=true
    username: root
    password: Vamsi@243
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-O:
          destination: send-communication



  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

#  mail:
#    host: smtp.example.com
#    port: 5870
#    username: vamsi
#    password: "jreo zura jziq fkms"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "user-service"
    description: "user-service microservice"
    version: "1.0.0"



