spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?createTableIfNotExists=true
    username: root
    password: Vamsi@243
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
